In [178]:
import numpy as np
def solve_jacobi(A: np.ndarray, b: np.ndarray, n: int) -> list:
    len_b = len(b) 
    x = np.array([n] * len(b), dtype = float) #initial guess
    row_A = len(A) #number of rows of matrix A 
    col_A = len(A[0])
    count = 0
    while count <11:
        tmp_vec = np.array([0] * len(b), dtype = float)
        for i in range(row_A):
            sum_element = 0
            for j in range(col_A):
                if j != i:
                    sum_element += A[i][j] * x[j]              #creating the total (j!=!) aijx[j] element of the algorith
            element = (1 / A[i][i]) * (b[i] - sum_element)
            tmp_vec[i] = float(round(element,4))
        x = tmp_vec.copy()
        print(x)
        count += 1    
    

    return x

In [181]:
A =[[5, -2, 3, 20], [-3, 9, 1, -7], [2, -1, -7, 19], [8,2,-1,1]]
b = [-1,2,3,7]
n=2

z = solve_jacobi(A,b,n)
print(z)

[ -8.6      2.2222   5.2857 -11.    ]
[ 41.5175 -11.7873 -33.0603  76.6413]
[-291.6439   77.3447  221.1439 -334.6257]
[ 1236.5543  -381.8284 -1003.0744  2406.6057]
[ -9177.5095   2395.6641   6939.635  -10124.852 ]
[ 37293.6926 -11704.9031 -30446.553   75575.3828]
[-288715.7606   74595.2567  217460.2231 -305379.2876]
[1120878.9192 -357917.8353 -922033.7489 2378002.7945]
[-9101958.2628  2325632.452   6825960.8242 -9173222.4319]
[ 33527566.0139 -10927154.5151 -27831539.7405  74990369.0226]
[-2.87633414e+08  7.25940914e+07  2.14685614e+08 -2.74197752e+08]
[-2.87633414e+08  7.25940914e+07  2.14685614e+08 -2.74197752e+08]


In [46]:
print(len(A))

A = [1,1,1]
A[1] = 6 
print(A)


3
[1, 6, 1]


In [ ]:
#this is correct per comparison to everything here https://atozmath.com/